


BUILD_ROOT:=$(dir $(lastword $(MAKEFILE_LIST)))
BUILD_TOOLS:=$(BUILD_ROOT)bld/
INCLUDE_PATHS=$(BUILD_ROOT)inc/

BIN_STAGING=$(BUILD_ROOT)bin/
LIB_STAGING=$(BUILD_ROOT)lib/

BUILD_LOGS=$(BUILD_ROOT)

#C_FLAGS=-static

LIB_PATHS=\
	$(abspath $(BUILD_ROOT)bin/$(O_AT)) \
	/usr/lib/gcc/x86_64-linux-gnu/4.7/ \

LIBS+=\
	pthread \
