

BUILD_ROOT:=$(dir $(lastword $(MAKEFILE_LIST)))
BUILD_TOOLS:=$(BUILD_ROOT)bld/
INCLUDE_PATHS=$(BUILD_ROOT)inc/

BIN_STAGING=$(abspath $(BUILD_ROOT)bin/)
LIB_STAGING=$(abspath $(BUILD_ROOT)lib/)

BUILD_LOGS=$(BUILD_ROOT)

include $(BUILD_ROOT)Makefile.config


#C_FLAGS=-static

LIBS+=\
	pthread \
